### ISSUE TITLE
Group References into ranges

### ISSUE THREAD

**Issue by justyn** [SchrodingersGat/KiBoM#13]
For boards where there are many identical components, it would be good to have the option to group references together like KiField does.

For example instead of:

R1, R4, R5, R6, R7, R8, R9, R10

you could have:

R1, R4-R10

**Comment by SchrodingersGat** [comment]
I like that - it would be nice to have that as an option flag (I wouldn't want to use such a feature all the time)

**Comment by schneidersoft** [comment]
Let me know if you'd rather want R8,R11,R12,R21-R42 or R8,R11-R12,R21-R42
... should groups of 2+ get a - or only groups of 3+

**Comment by SchrodingersGat** [comment]
I think 3+ makes sense. Are you going to implement this? :)

**Comment by schneidersoft** [comment]
Yup. Should be up momentarily.

**Comment by KarlZeilhofer** [comment]
@schneidersoft how about the implementation of this feature?

I've one additional feature request: 
```
C201 C204-C211 C308 C310 C313 C412 C601 C602-C610 C613
```
would be still a very wide cell in the spread sheet. I would prefer a line break after N entries, e.g. 5
```
C201 C204-C211 C308 C310
C313 C412 C601 C602-C610
C613
```

Once I've written my own BOM-tool in C, which had this feature, it was exported with \n, which 
was displayed correctly in libre office calc.

**Comment by schneidersoft** [comment]
Ok. so you want to word wrap to N words. where each entry C201, C202 etc. is a word.
your example works when N is 4.
What happens when N is 2?

C201 C204-
C211 C308
C310 C313
C412 C601
C602-C610
C613

When N is 3
C201 C204-C211
C308 C310 C313
C412 C601 C602-
C610 C613

Uggly much?
Are you suggesting we alter the hyphenation?
N=2:
C201 C204
C205-C211
C308 C310
C313 C412
C601 C602
C603-C610
C613

**Comment by KarlZeilhofer** [comment]
I would prefer the last option. setting N to 2 is not used in daily life, I think. 

If we use N=5, then in worst case there are some lines with only 4 entries...

```
C201 C204-C211 C301 C308 
C310 C313 C412 C601 
C602-C610 C613 C617 C619
C621
```

Are you going to implement this?

**Comment by schneidersoft** [comment]
Yes. I have implemented it.

**Comment by KarlZeilhofer** [comment]
@schneidersoft Thanks! Where can I find it and how can I use it?

**Comment by KarlZeilhofer** [comment]
@SchrodingersGat I saw, this ferature wasn't merged into this master branch, why not?

**Comment by schneidersoft** [comment]
you can always pull from my repo. But it would be better to get the changes merged into this one.

**Comment by SchrodingersGat** [comment]
@schneidersoft I can't see an open PR for this feature - have I mistakenly closed it, or have you not opened one?

**Comment by schneidersoft** [comment]
PR #19 incorporates this feature and a few others.
I made a bunch of changes one after the other., and only one PR. I don't know if that's the correct way of doing things.

**Comment by SchrodingersGat** [comment]
#19 is merged now - OK to close this issue?

**Comment by schneidersoft** [comment]
Sure

**Comment by KarlZeilhofer** [comment]
Looks great now. Here's an example:
![2018-05-27_001](https://user-images.githubusercontent.com/2773445/40582411-fb5cfa1e-6175-11e8-9629-d736a01fc95a.png)

3 things I'd like to notice:
1. This feature is not documented in the README.md
2. `alt_wrap` only works, if `use_alt` is set to 1. For documentation only, this is quite okay, but in some cases, where we do a manual pick and place, I like to check every reference with a pencil on paper. But this doesn't work any more, if the references are grouped in ranges. 
3. perhaps the options should have a better naming: 
   `wrap_ref_count` instead of `alt_wrap` and  
   `use_ref_ranges` instead of `use_alt`
